### ISSUE TITLE
issue - running yarn test:cypress with build:packages (lerna)

### ISSUE THREAD

**Issue by stephyswe** [toptal/picasso#2432]
Hi, how to run "yarn test:cypress" in picasso? 
I tried to run it and get the following error. Not sure what is going on.

`Stephanie@DESKTOP-90ROKD9 MINGW64 /d/reactpicasso (master)
$ yarn run test:cypress
yarn run v1.22.17
$ yarn build:package && yarn test:setup cypress run-ct
$ lerna run build:package --stream --parallel
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 7 packages: "yarn run build:package"
@toptal/picasso-charts: $ cross-env NODE_ENV=production node ../../bin/build.js --tsConfig=./tsconfig.build.json
@toptal/picasso-codemod: $ ./bin/build.sh
@toptal/picasso-forms: $ cross-env NODE_ENV=production node ../../bin/build.js --tsConfig=./tsconfig.build.json
@toptal/picasso: $ cross-env NODE_ENV=production node ../../bin/build.js --tsConfig=./tsconfig.build.json
@toptal/picasso-shared: $ cross-env NODE_ENV=production node ../../bin/build.js --tsConfig=./tsconfig.build.json
@toptal/picasso-provider: $ cross-env NODE_ENV=production node ./bin/build.js
@topkit/analytics-charts: $ cross-env NODE_ENV=production node ../../bin/build.js --tsConfig=./tsconfig.build.json
@toptal/picasso-charts: Building @toptal/picasso-charts:21.0.0
@toptal/picasso-charts: Removing: dist-package
@toptal/picasso-charts: node:internal/fs/utils:344
@toptal/picasso-charts:     throw err;
@toptal/picasso-charts:     ^
@toptal/picasso-charts: Error: ENOENT: no such file or directory, stat 'dist-package'
@toptal/picasso-charts:     at Object.statSync (node:fs:1536:3)
@toptal/picasso-charts:     at __node_internal_ (node:internal/fs/utils:793:8)
@toptal/picasso-charts:     at Object.rmdirSync (node:fs:1156:15)
@toptal/picasso-charts:     at clean (D:\reactpicasso\bin\build.js:25:8)
@toptal/picasso-charts:     at compile (D:\reactpicasso\bin\build.js:31:3)
@toptal/picasso-charts:     at Object.<anonymous> (D:\reactpicasso\bin\build.js:48:1)
@toptal/picasso-charts:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@toptal/picasso-charts:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@toptal/picasso-charts:     at Module.load (node:internal/modules/cjs/loader:981:32)
@toptal/picasso-charts:     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
@toptal/picasso-charts:   errno: -4058,
@toptal/picasso-charts:   syscall: 'stat',
@toptal/picasso-charts:   code: 'ENOENT',
@toptal/picasso-charts:   path: 'dist-package'
@toptal/picasso-charts: }
@toptal/picasso-forms: Building @toptal/picasso-forms:28.0.0
@toptal/picasso-forms: Removing: dist-package
@toptal/picasso-forms: node:internal/fs/utils:344
@toptal/picasso-forms:     throw err;
@toptal/picasso-forms:     ^
@toptal/picasso-forms: Error: ENOENT: no such file or directory, stat 'dist-package'
@toptal/picasso-forms:     at Object.statSync (node:fs:1536:3)
@toptal/picasso-forms:     at __node_internal_ (node:internal/fs/utils:793:8)
@toptal/picasso-forms:     at Object.rmdirSync (node:fs:1156:15)
@toptal/picasso-forms:     at clean (D:\reactpicasso\bin\build.js:25:8)
@toptal/picasso-forms:     at compile (D:\reactpicasso\bin\build.js:31:3)
@toptal/picasso-forms:     at Object.<anonymous> (D:\reactpicasso\bin\build.js:48:1)
@toptal/picasso-forms:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@toptal/picasso-forms:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@toptal/picasso-forms:     at Module.load (node:internal/modules/cjs/loader:981:32)
@toptal/picasso-forms:     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
@toptal/picasso-forms:   errno: -4058,
@toptal/picasso-forms:   syscall: 'stat',
@toptal/picasso-forms:   code: 'ENOENT',
@toptal/picasso-forms:   path: 'dist-package'
@toptal/picasso-forms: }
@toptal/picasso-shared: Building @toptal/picasso-shared:7.2.2
@toptal/picasso-shared: Removing: dist-package
@toptal/picasso: Building @toptal/picasso:18.3.0
@toptal/picasso: Removing: dist-package
@toptal/picasso-shared: node:internal/fs/utils:344
@toptal/picasso-shared:     throw err;
@toptal/picasso-shared:     ^
@toptal/picasso-shared: Error: ENOENT: no such file or directory, stat 'dist-package'
@toptal/picasso-shared:     at Object.statSync (node:fs:1536:3)
@toptal/picasso-shared:     at __node_internal_ (node:internal/fs/utils:793:8)
@toptal/picasso-shared:     at Object.rmdirSync (node:fs:1156:15)
@toptal/picasso-shared:     at clean (D:\reactpicasso\bin\build.js:25:8)
@toptal/picasso-shared:     at compile (D:\reactpicasso\bin\build.js:31:3)
@toptal/picasso-shared:     at Object.<anonymous> (D:\reactpicasso\bin\build.js:48:1)
@toptal/picasso-shared:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@toptal/picasso-shared:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@toptal/picasso-shared:     at Module.load (node:internal/modules/cjs/loader:981:32)
@toptal/picasso-shared:     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
@toptal/picasso-shared:   errno: -4058,
@toptal/picasso-shared:   syscall: 'stat',
@toptal/picasso-shared:   code: 'ENOENT',
@toptal/picasso-shared:   path: 'dist-package'
@toptal/picasso-shared: }
@toptal/picasso: node:internal/fs/utils:344
@toptal/picasso:     throw err;
@toptal/picasso:     ^
@toptal/picasso: Error: ENOENT: no such file or directory, stat 'dist-package'
@toptal/picasso:     at Object.statSync (node:fs:1536:3)
@toptal/picasso:     at __node_internal_ (node:internal/fs/utils:793:8)
@toptal/picasso:     at Object.rmdirSync (node:fs:1156:15)
@toptal/picasso:     at clean (D:\reactpicasso\bin\build.js:25:8)
@toptal/picasso:     at compile (D:\reactpicasso\bin\build.js:31:3)
@toptal/picasso:     at Object.<anonymous> (D:\reactpicasso\bin\build.js:48:1)
@toptal/picasso:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@toptal/picasso:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@toptal/picasso:     at Module.load (node:internal/modules/cjs/loader:981:32)
@toptal/picasso:     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
@toptal/picasso:   errno: -4058,
@toptal/picasso:   syscall: 'stat',
@toptal/picasso:   code: 'ENOENT',
@toptal/picasso:   path: 'dist-package'
@toptal/picasso: }
@toptal/picasso-charts: error Command failed with exit code 1.
@toptal/picasso-charts: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@topkit/analytics-charts: Building @topkit/analytics-charts:18.0.0
@topkit/analytics-charts: Removing: dist-package
@topkit/analytics-charts: node:internal/fs/utils:344
@topkit/analytics-charts:     throw err;
@topkit/analytics-charts:     ^
@topkit/analytics-charts: Error: ENOENT: no such file or directory, stat 'dist-package'
@topkit/analytics-charts:     at Object.statSync (node:fs:1536:3)
@topkit/analytics-charts:     at __node_internal_ (node:internal/fs/utils:793:8)
@topkit/analytics-charts:     at Object.rmdirSync (node:fs:1156:15)
@topkit/analytics-charts:     at clean (D:\reactpicasso\bin\build.js:25:8)
@topkit/analytics-charts:     at compile (D:\reactpicasso\bin\build.js:31:3)
@topkit/analytics-charts:     at Object.<anonymous> (D:\reactpicasso\bin\build.js:48:1)
@topkit/analytics-charts:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@topkit/analytics-charts:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@topkit/analytics-charts:     at Module.load (node:internal/modules/cjs/loader:981:32)
@topkit/analytics-charts:     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
@topkit/analytics-charts:   errno: -4058,
@topkit/analytics-charts:   syscall: 'stat',
@topkit/analytics-charts:   code: 'ENOENT',
@topkit/analytics-charts:   path: 'dist-package'
@topkit/analytics-charts: }
@toptal/picasso-forms: error Command failed with exit code 1.
@toptal/picasso-forms: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build:package exited 1 in '@toptal/picasso-charts'
lerna WARN complete Waiting for 6 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 
Stephanie@DESKTOP-90ROKD9 MINGW64 /d/reactpicasso (master)
$`

**Comment by denieler** [comment]
Hey @stephyswe 👋  It's happening most likely because of your permissions for your folders. So it can't create `dist-package` folders inside each Picasso package. Try to configure your folder permissions and it should work for you 😃  Also, you have to have Docker installed and configured to be able to run visual tests in Docker image, but there is also an opportunity to run visual tests without Docker image, directly on your machine, however, generated visual snapshots can have differences from the ones committed to the repo.

**Comment by stephyswe** [comment]
> Hey @stephyswe 👋 It's happening most likely because of your permissions for your folders. So it can't create `dist-package` folders inside each Picasso package. Try to configure your folder permissions and it should work for you 😃 Also, you have to have Docker installed and configured to be able to run visual tests in Docker image, but there is also an opportunity to run visual tests without Docker image, directly on your machine, however, generated visual snapshots can have differences from the ones committed to the repo.

Thanks so much! Do you know how to change permission ? Using Windows 10 

Ive Docker installed! Need to look up how configure it to fit visual testing !

**Comment by TomasSlama** [comment]
@stephyswe and are you using Linux subsystem (WSL)? or working directly on windows?

**Comment by TomasSlama** [comment]
@stephyswe either way, as first I would try to create manually empty `dist-package` inside all packages. It solved the issue lately for someone.

**Comment by separatio** [comment]
@stephyswe It's a little hard to create the `dist-package` inside all packages.

I recommend you go to `bin/build.js` in `picasso`, and comment out lines 23 to 31, effectively commenting out the `clean()` function. Run the script again, and the folders should be created by themselves. After everything is set up, uncomment the code.

You'll not have this issue moving forward afterwards. 👍

**Comment by separatio** [comment]
Will be fixed with https://github.com/toptal/picasso/pull/2439
