### ISSUE TITLE
[Form.Select] Open the selector if user starts typing while it is focused.

### ISSUE THREAD

**Issue by rhuankarlus** [toptal/picasso#2523]
**Form.Select**
https://picasso.toptal.net/?path=/story/picasso-forms-form--form

**Is your feature request related to a problem? Please describe.**
Yes, for a better UX we must provide the same functionalities of the wrapped components. In this case if we focus on a pure HTML selector and start typing the selector will provide us with the most accurate value close to what we typed. Our selector, on the other hand, does not provide the same functionality.

https://user-images.githubusercontent.com/4607181/158618330-f1cc8d89-1fde-4757-a161-471b2c00d4c2.mp4

**Describe the solution you'd like**
When the user focus on the Selector and start typing the selector must calculate the most accurate value and place it as selected.

**Comment by LashaJini** [comment]
Ticket created.
