### ISSUE TITLE
Language improvements

### ISSUE THREAD

**Issue by piotrd** [toptal/picasso#839]
The amount of language causing confusion keeps growing in Picasso codebase. I am not even referring to documentation (which itself could use a language review), but rather to names of components, variables, classes etc.. Encouraged by @bytasv I created this issue as a place to gather them, and hopefully one day Picasso will improve also in this area. Of course some items listed below might be false positives, but we can always clarify them. Feel free to add your findings.

Issue | Suggestion for improvement | Comment
-------- | --------- | ----
`CompoundedComponentWithRef` | `CompoundComponentWithRef` | _Compound_ is an adjective, while _compounded_ doesn't seem to be an English word.
`ShowMore` | `ShowMoreContainer`? | I'm not sure about this one, but it stands out on the list of components, because all other are named using nouns and `ShowMore` doesn't say whether it is a container, a link, text or whatever.
~`Stepper` (component name)~ |  | ~According to dictionaries, stepper is a dancer (or horse) who steps (specific type of dance). There seems to be no connection of that word with "something containing/consisting of steps".~
`Tabs` | `TabBar`? | All other components have singular names, so why have this as plural?
`TagSelector` | `TagSelect`? | There is a `YearSelect`, `AccountSelect` and `Select`. All of them do similar things. It makes sense to follow the same pattern.

**Comment by separatio** [comment]
Synced with @piotrd.This is no longer an actual issue. Closing.
